packages:
  - "."

networkConcurrency: 8
fetchRetries: 5
fetchRetryFactor: 2
fetchRetryMintimeout: 10000
fetchRetryMaxtimeout: 120000
fetchTimeout: 120000

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  devalue: 5.8.1
  ws: 8.20.1
  yaml: 2.8.4
